services:
  traefik:
    image: "traefik:${TRAEFIK_VERSION}"
    container_name: traefik
    restart: always
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_HTTPS_PORT}:443"
    volumes:
      - ./data/traefik/conf:/etc/traefik
      - ./data/traefik/logs:/var/log
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - externe
      - interne
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]

  exemple:
    image: "exemple:${EXEMPLE_VERSION}"
    container_name: exemple
    restart: always
    environment:
      TZ: ${TIMEZONE}
    depends_on:
      traefik:
        condition: service_healthy
    networks:
      - interne
      - externe
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.EXEMPLE.rule=Host(`${EXEMPLE_HOST}`)"
      - "traefik.http.routers.EXEMPLE.entrypoints=https"
      - "traefik.http.services.EXEMPLE.loadbalancer.server.port=${EXEMPLE_PORT}"
      - "traefik.http.routers.EXEMPLE.tls.certresolver=letsencrypt"
      - "traefik.http.routers.EXEMPLE.middlewares=headers@file"

networks:
  interne:
    name: interne
    driver: bridge
    internal: true
  externe:
    name: externe
